### PR TITLE
Improved tests

### PR DESCRIPTION
**Pull request by orangemug**
This implements a lot more complete testing via [webdriverio](http://webdriver.io/). Tracking issue #279

It works by assigning data attributes in the html for each block of functionality in the editor. The idea being that these won't change very much as we change the UI. The data attribute used is `data-wd-key` and this is the majority of the changes to the apps source.

The tests are somewhat complete, there are 25 passing tests and 35 pending. The pending test range in completeness, mostly they are flaky in some way. All the passing tests have been run 100 times locally and multiple times on circleCI to check they are stable. The pending ones are mostly just flaky tests which need investigating and fixing.

The new testing infrastrucute is as follows

 - CircleCI (linux) - build & test
 - Appveyor (windows) - build
 - Travis (osx) - build

CircleCI is beacuse we get

 - free artifact hosting, meaning we can store
   - builds - https://circleci.com/gh/orangemug/editor/267#artifacts/containers/0
   - coverage - https://267-84182601-gh.circle-artifacts.com/0/artifacts/coverage/index.html
   - screenshots - https://267-84182601-gh.circle-artifacts.com/0/artifacts/screenshots/settings.png
 - speedier builds - this is important for quick turn around over the months I've seen 40min delays for tests in the other 2 platforms. CircleCI has been fast throughout

We only _build_ on the other environments because testing in webdriver is

 - Slow on these enviroments
 - Testing on chrome in multiple enviroments isn't necessary

Note that we'll add [saucelabs](https://saucelabs.com/) for better cross browser testing in the future.

### CODE REVIEW

**Comment by orangemug** [comment]
If anyone/everyone has time can they try running the tests on their local machines.

See instructions here <https://github.com/orangemug/editor/blob/8ba2123a26e7654155504e55e4d47e09f22c73ca/README.md#tests>

Please report back success/failure in the comments below.

**Comment by orangemug** [comment]
@oterral if you have time would you mind checking you can run the new tests locally, see comment <https://github.com/maputnik/editor/pull/280#issuecomment-380148760>

Instructions on how to grab PR are outlined here <https://help.github.com/articles/checking-out-pull-requests-locally>

**Comment by gregorywolanski** [comment]
About [“Tests” section in README](https://github.com/orangemug/editor/blob/8ba2123a26e7654155504e55e4d47e09f22c73ca/README.md#tests):

```
$ ./node_modules/.bin/selenium-standalone
No action provided
Usage: selenium-standalone action [options]

$ ./node_modules/.bin/selenium-standalone help
Invalid action "help (Valid actions are [start, install])
Usage: selenium-standalone action [options]
```

Results:

```
[chrome #0-0] 25 passing (1m, 49s)
[chrome #0-0] 35 pending
```

**Comment by gregorywolanski** [comment]
@pjsier @oterral Your turn! :D

**Comment by orangemug** [comment]
Thanks @pjsier and @gregorywolanski for your help. Merged!

**Pull request merged**
