### PR TITLE
Scroll selected <LayerListItem/> into view

### LINKED ISSUE #630: Scroll to layer list item after click on layer in <FeatureLayerPopup />
I found very simple UI issue here.

1. Click map feature and see selected layer list popup.
2. And then clicking some layer.
3. Changed selected layer view left side, but I couldn't found layer from list (but it changed focused item)

If scroll to selected layer from list, it makes sense.
Please consider for it.

스크린샷 2020-04-02 오후 7 20 01

### PR DESCRIPTION
**Pull request by orangemug**
Scrolls `<LayerListItem/>` into view when selected. This PR also fixes general selection bugs from `<FeatureLayerPopup/>` created by #620  

Demo <https://2434-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

Fixes #630

### CODE REVIEW

**Comment by orangemug** [comment]
I'm going to release a new `1.7.0` beta soon so merging this in now. Feel free to test/report errors here, or in a new ticket

AppVeyor is failing with

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 500 status code downloading arm64 node.lib
```

Which appears to be a general test setup issue.

**Comment by pathmapper** [comment]
@orangemug nice improvement, works great.

**Comment by Jinkwon** [comment]
@orangemug 
Thanks for your huge effort.
On select layer from left list, it scroll to layer too. It's not what I expected.
I think it has to only scroll to from FeatureLayer.

blink

**Comment by orangemug** [comment]
@Jinkwon yeah I noticed that after I merged this PR, should be fixed in `v1.7.0-beta3` see https://maputnik.github.io/releases/v1.7.0-beta3

FYI the tracking ticket for release `v.1.7.0` is issue #629

**Comment by Jinkwon** [comment]
@orangemug It works very fine. :) Thanks for your effort!!! 
Really helpful function for me.

**Pull request merged**
