### PR TITLE
Ability to delete properties completely

### LINKED ISSUE #507: Regression: Map doesn't update when fill-pattern is changed

### PR DESCRIPTION
**Pull request by orangemug**
This fix allows you to remove properties which display as `AutocompleteInput`, `ColorField` and `InputBlock`, where as before they would be set to an empty string `""`   

Demo: <https://1416-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

Fixes #507
Reference #509 (`text-font` still requires further fixes)

### CODE REVIEW

**Comment by pathmapper** [comment]
This doesn't work (map is not updated) if you modify (don't delete) e.g. the name of a  `fill-pattern` in the `pattern` field or in the JSON editor.

Also after a property (tested with `fill-pattern`) is deleted completely and you type a valid value in the `pattern` field, the map is not updated. The map is only updated if a proposed value in the `pattern` field is selected.

It's not possible anymore to set an empty string as value via the `pattern` field. The only option is to use the JSON editor.

**Comment by orangemug** [comment]
> This doesn't work (map is not updated) if you modify (don't delete) e.g. the name of a fill-pattern in the pattern field or in the JSON editor.

Yeah I agree but I think this is an existing issue. Try in the current build of `master` https://1583-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

> Also after a property (tested with fill-pattern) is deleted completely and you type a valid value in the pattern field, the map is not updated. The map is only updated if a proposed value in the pattern field is selected.

I think this is also an existing issue in `master`

> It's not possible anymore to set an empty string as value via the pattern field. The only option is to use the JSON editor.

So I thought this was what was originally reported in #507, and the intended functionality when would you want an empty string?

**Comment by pathmapper** [comment]
> Yeah I agree but I think this is an existing issue. Try in the current build of master https://1583-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Right, this is an existing issue in `master` and not introduced by this PR, but in `1.5` the issue is not there. Here's a `fill-pattern` test case:
https://maputnik.github.io/editor/#17.96/50.775437/6.084083 (`OSM Liberty` style, `road_area_pattern` layer)

> I think this is also an existing issue in `master`

Right, but also in `1.5` not present.

> So I thought this was what was originally reported in #507 (although the title is a little confusing), and the intended functionality when would you want an empty string?

Sorry for the confusion. I understood that in #507 originally the regression since `1.5` was reported (in `1.5`, if you change a `fill-pattern` with a valid value to an empty string the pattern is not shown anymore on the map) and later the ability to delete properties completely was requested.

So my intend was that #507 is about the regression since `1.5` (as `1.5` is working fine) and #509 is about the possibility to delete a property completely (maybe by adding a button for this task next to the input field).

Regarding empty string as value:
1. Empty string is a valid value for `fill-pattern` according to the style spec (it says it's a string, and empty string is a string).
2. `fill-pattern` disables other properties (e.g. `fill-color`), so a use case is to create a style with empty string as `fill-pattern` value and set the `fill-pattern` value later programatically in an app with https://docs.mapbox.com/mapbox-gl-js/api/#map#setpaintproperty

**Comment by orangemug** [comment]
Hey @pathmapper thanks for the feedback.

So regarding the updating issues with `fill-pattern` downgrading `mapbox-gl` to `^0.47.0` fixes the issue, so it look like the problem is upstream. I'll see if I can get a test case outside this PR. 

As for the `fill-pattern` empty string (`""`) I feel like is a bit of an edge case. Do people use it like that, because you could achieve the same thing other ways. For example setting `{"layout": {"visibility": "none"}`, and then enabling the layer when you need it.

Also remember that initially the text box is blank (with a new layer), but the JSON won't have `{"fill-pattern": ""}` until you
 
 1. Enter something in the `<input/>`
 2. Remove the text again
 3. Now the JSON will be set to `{"fill-pattern": ""}` 

Since the `fill-pattern` as empty string seems like a bit of an edge case. I think we should prioritise removing the value if the `<input/>` is `""`. If a user really needs `""` they can always add it back in the the JSON editor.

Thoughts?

**Comment by pathmapper** [comment]
> regarding the updating issues with fill-pattern downgrading mapbox-gl to ^0.47.0 fixes the issue, so it look like the problem is upstream.

Good find @orangemug ! Looks like this is fixed in mapbox-gl `v1.1.0-beta.1` :smile: 

> Also remember that initially the text box is blank (with a new layer), but the JSON won't have {"fill-pattern": ""}

Very good point. 

Let's go for "removing the value if the `<input/>` is `""`. If a user really needs `""` they can always add it back in the the JSON editor."

**Comment by orangemug** [comment]
> Looks like this is fixed in mapbox-gl v1.1.0-beta.1

Nice spot @pathmapper 

Updated to `mapbox-gl@^1.1.0-beta.1` heres the new build <https://1432-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

**Comment by pathmapper** [comment]
Did some tests and it works great so far. :tada:

**Comment by pathmapper** [comment]
@orangemug it's not possible to delete a font value in the `Font` field anymore, but I guess this is what you've meant with 

> Reference #509 (text-font still requires further fixes)

grafik

**Comment by orangemug** [comment]
> it's not possible to delete a font value in the Font field anymore, but I guess this is what you've meant with

Thanks @pathmapper it was what I meant... but I didn't quite realise how badly I'd broken it. I've push up a new improved `<FontInput/>` it basically removes empty values and always has a empty input at the bottom of the list for entering additional fallback fonts.

It's still a little awkward to use but seems better than before (`<FontInput/>` is probably up for a rewrite soonish). Let me know what you think. 

Link: <https://1445-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

**Comment by pathmapper** [comment]
Thanks @orangemug , looks good!

I think like it is now this PR closes also https://github.com/maputnik/editor/issues/129 and https://github.com/maputnik/editor/issues/509.

**Comment by orangemug** [comment]
Yay merging! Thanks for all the help @pathmapper really great work testing this. 

Fixes #129 and #509.

**Comment by pathmapper** [comment]
Fixed also #395 :tada:

**Pull request merged**
