### PR TITLE
Link to OSM from debug panel

### PR DESCRIPTION
**Pull request by orangemug**
This adds a link to OSM `https://www.openstreetmap.org/#map={ZOOM}/{LAT}/{LNG}` from the debug panel

To open the debug panel focus the editor then press `ESC` follow by `!`

Demo: <https://1981-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>

Screenshot 2020-01-19 at 16 06 14

### CODE REVIEW

**Comment by pathmapper** [comment]
This is a very cool feature, closes https://github.com/maputnik/editor/issues/82.

There's something not working right:

https://1986-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#5.56/40.111/-3.707

results in this link:

https://www.openstreetmap.org/#map=7/2.842170943040401e-14/0

which gets redirected to NULL island:

https://www.openstreetmap.org/#map=7/0.000/0.000

Maybe this could be fixed by limiting the center coordinates to 5 or 6 digits after the decimal point.

**Comment by orangemug** [comment]
> Maybe this could be fixed by limiting the center coordinates to 5 or 6 digits after the decimal point.

Yup spot on, fixed in https://1996-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Also fixed an issue where a zoom centre point change without a pan wasn't updating the centre

**Comment by pathmapper** [comment]
Looks good now :+1:

**Comment by orangemug** [comment]
Thanks

**Pull request merged**
