### PR TITLE
Update OpenMapTiles styles to the latest version fixes #901

### LINKED ISSUE #901: Update the Gallery styles (MapTiler Basic, Dark Matter, Position, OSM Bright and Toner) to the latest version
Update the Gallery styles (MapTiler Basic, Dark Matter, Position, OSM Bright, and Toner) to the latest version.

The new [version (v3.15) of OpenMapTiles](https://www.maptiler.com/news/2024/04/openstreetmap-data-prepared-for-advanced-cartography/) was released at the end of April, and the styles (MapTiler Basic, Dark Matter, Position, etc.) have also been updated.

The main change in the styles is to use https://api.maptiler.com/tiles/v3-openmaptiles/ as a data source (based exclusively on the schema (https://docs.maptiler.com/schema/omt -planet /) from OpenMapTiles) instead of the data source https://api.maptiler.com/tiles/v3/ a schema (https://docs.maptiler.com/schema/planet/) from MapTiler (based on OpenMapTiles )

### PR DESCRIPTION
**Pull request by bolollo**
Update version numbers of OpenMapTiles styles.

These styles are updated with the latest version (v3.15) of OpenMapTiles.

Fixes #901

### CODE REVIEW

**Comment by HarelM** [comment]
does this change requires an image change in the selection menu?

**Comment by bolollo** [comment]
> does this change requires an image change in the selection menu?

No need to change images

**Comment by HarelM** [comment]
You can ignore the FF tests. 
Let me know if there's anything else you would like to change as part of this PR before I merge.

**Review by HarelM — APPROVED** [review]

**Comment by bolollo** [comment]
I have already added the tileset url change.

Right now, there is nothing more to add. Thank you so much.

It would also be good to add the OpenStreetMap style https://openmaptiles.org/styles/#osm-openmaptiles, but at the moment, it is only in https://cloud.maptiler.com/maps/openstreetmap/. For that, I will open another issue now. The MapTiler API key is necessary, and I have to see how to do it without putting hardcoded in the style.json.

**Pull request merged**
