### PR TITLE
Added new CI workflow using GitHub actions

### LINKED ISSUE #679: Github Actions
For the upcoming release we are having a few issues related to our workflow on our list:

- Automate desktop builds (https://github.com/maputnik/editor/issues/668)
- Automate deployments (#173)
- Bot for posting test build link to PR (#456)
- Provide docker images for releases on dockerhub (#489)

We could investigate if it's possible and suitable to use Github Actions for all these tasks:
https://github.com/features/actions

OpenMapTiles is now using the GitHub Actions Bot to post performance evaluation results for PRs, e.g. https://github.com/openmaptiles/openmaptiles/pull/841#issuecomment-621738878.

It should be also possible to automate publishing docker images with GitHub Actions for GitHub Packages:

https://help.github.com/en/packages

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

### PR DESCRIPTION
**Pull request by orangemug**
Added new a CI workflow using GitHub actions as discussed in #679.

Also

 - Fixed screenshot tests
 - Fixed code coverage
 - Removed appveyor
 - Removed circleci
 - Updated wdio related dependencies
 - Added docker image deploy to the GitHub registry

Fixes #679 and #489

### CODE REVIEW

**Comment by orangemug** [comment]
So I've had to remove the 'demo link' functionality from this PR, this issue is explained by @nyurik over in this repo https://github.com/nyurik/auto_pr_comments_from_forks

So we could add the cron hack explained in the link above (which is pretty smart). The downside is that it takes a while for the link to be added to the pull request. Another option we could setup a little server that creates some sort of event on the target repo (`maputnik/editor`) repo (rather than the fork)  🤔

**Comment by orangemug** [comment]
So @pathmapper I've removed the auto-commenting for now as it doesn't work on forks. This PR seems to give us the same functionality as we had before with CircleCI/AppVeyor, so I suggest we merge and I'll remove the CircleCI/AppVeyor integrations from the repo. Is there anything I'm missing? 🤔

**Comment by pathmapper** [comment]
Great work @orangemug, let's merge. We could decide on the remaining tasks later.

Regarding manually posting a demo link until there is an automatic solution:
The demo link for this PR would be 
https://1lkhr.sse.codesandbox.io
based on 
https://codesandbox.io/embed/github/maputnik/editor/tree/d2853f3?view=preview
right?

**Comment by orangemug** [comment]
@pathmapper so the link would be

```
https://codesandbox.io/embed/github/<user>/<repo>/tree/<branch>?view=preview
```

So this branch would be https://codesandbox.io/embed/github/orangemug/editor/tree/feature/github-actions-ci?view=preview

**Pull request merged**
