### PR TITLE
Add expand/collapse all layer groups feature (#130)

### PR DESCRIPTION
**Pull request by gregorywolanski**
Response to #130:

31961927-7f10b83c-b8fc-11e7-9059-8943812eeb96

### CODE REVIEW

**Comment by orangemug** [comment]
First off sorry it took me so long to review this pull request, I was planning to change the UI a little and wanted to make sure it wouldn't conflict (it doesn't).

The functionality of the expand/collapse looks good. Although I have a couple of comments about the UI.

The button is a toggle button. Toggle buttons usually represent the state, but here we actually have 3 states rather than 2.

 - All expanded
 - All collapsed
 - Some expanded / some collapsed (the missing one)

The button also feels like something you wouldn't use often, so should it be such a big part of the main UI?

An alternative would be to put a little menu kind of like the one shown here <https://material.io/guidelines/components/menus.html#menus-usage> with 2 options

 - Expand all
 - Collapse all

What do you think @gregorywolanski does this make sense and is it worth the extra effort?

**Comment by orangemug** [comment]
Thanks for the detailed reply and I think it makes sense. My reason for wanting a context menu was additionally that I think there may be more options later down the road... but that's not the problem at hand so I probably shouldn't try to predict the future.

Lets stick with your solution.

Although there is a styling issue, expand should sit to the right with the layers button (as in your screenshot)

screen shot 2017-11-29 at 21 47 46

**Comment by gregorywolanski** [comment]
@orangemug I’ll fix it. What browser do you use?

**Comment by orangemug** [comment]
> What browser do you use, on which OS?
Latest chrome/firefox on the mac

**Comment by gregorywolanski** [comment]
Thanks, @orangemug. Silly mistake. Fixed. :)

**Comment by gregorywolanski** [comment]
Happy New Year, @orangemug! :)

I’m looking forward to reading about the changes in the UI you have planned.

**Pull request merged**
