### PR TITLE
Fix the size of the logo in the survey modal

### PR DESCRIPTION
**Pull request by orangemug**
So it doesn't cause a visual jump when it loads.

### CODE REVIEW

**Comment by orangemug** [comment]
Is the visual jump from the font loading in and changing the line height?

**Comment by pathmapper** [comment]
Hard to tell, could be related to the `<h1>` font, here is how it looks:

visual_jump

**Comment by pathmapper** [comment]
Adding the following to [_modal.scss](https://github.com/maputnik/editor/blob/master/src/styles/_modal.scss)

```
.maputnik-modal-survey__header {
  max-height: 20px;
 }
```

and adding this class to the `<h1>` tag: https://github.com/maputnik/editor/blob/master/src/components/modals/SurveyModal.jsx#L30 
fixes the visual jump for me.

**Comment by orangemug** [comment]
So the typeface will swap in as it's loaded, browsers handle this different but it's basically a trade off between waiting for the typeface to load vs using the app. I've gone with  [`font-display: swap;`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) to prioritise a useable app over a pretty app on first load. The typeface loads last which means for those on slow connections it'll be usable quicker.

**Pull request merged**
