### PR TITLE
Added style formatting into the api store

### PR DESCRIPTION
**Pull request by orangemug**
This is a fix for #591. However at the moment that part is untested as I don't personally have maputnik/desktop setup and working. If someone has maputnik/desktop setup and wants to test the build, feel free. Otherwise I'll get round to it next week, when my brain is a little fresher

### CODE REVIEW

**Comment by pathmapper** [comment]
cc @kylebarron

**Comment by kylebarron** [comment]
It appears that building maputnik/editor doesn't allow me to test changing a local file. That's in maputnik/desktop right? I essentially haven't used Go at all, and I wasn't able to build maputnik/desktop correctly, and even so, I'm not sure how to modify the Makefile so that it builds from this branch.

**Comment by orangemug** [comment]
@kylebarron yeah that's where I got to as well. I haven't done any work with maputnik/desktop :)

Not to worry, if you feel like learning a bit of 'go' please feel free, else I'll dig into it. I'm happy either way.

**Comment by kylebarron** [comment]
I'm pretty busy, so figuring out Go isn't really high on my list at the moment.

**Comment by orangemug** [comment]
No worries @kylebarron, thanks for letting me know.

**Comment by pathmapper** [comment]
The makefile of Maputnik Desktop pulls the `public.zip` from the [latest editor release](https://github.com/maputnik/editor/releases/tag/v1.6.1) here:
 https://github.com/maputnik/desktop/blob/master/Makefile#L26 

The following should work:
1. Create a new build of Maputnik Editor incorporating the changes of this PR (or download the CI build artifacts: https://circleci.com/gh/orangemug/editor/2006#artifacts/containers/0)
2. Put the build in a `public.zip` with the same structure as the [original](https://github.com/maputnik/editor/releases/download/v1.6.1/public.zip) one
3. Modify the makefile of Maputnik Desktop to use your custom `public.zip`

**Comment by pathmapper** [comment]
ping @lukaswelte

**Comment by lukaswelte** [comment]
Yes that is how it pulls in the editor. 
If you would like to build that locally you need to have go set up and install the dependencies with go get (https://github.com/maputnik/desktop/blob/master/Makefile#L8-L17). 

However if this is a common scenario we can see how we can make it possible that circle ci is building an editor version for a branch. Would work easily if circle ci for editor project would save the release bundle as artifact for every branch and then invoke the desktop build and have the link to the zip forder as argument. 

Then each pull request in editor would have the preview version to download directly in it.
What do you think?

**Comment by pathmapper** [comment]
Thanks @lukaswelte 

> Then each pull request in editor would have the preview version to download directly in it.

From my side I think this would be great - for testing PRs also with Maputnik Desktop (especially when they are related to Desktop like this one) and also for having a Desktop version available for every Editor release. For the last three releases I built the Desktop versions locally and uploaded them manually to https://github.com/maputnik/editor/releases.
This means also that the Desktop version was built after a release without having tested it before which is not good.

I did not use `go` before and it took me a while to have a working set up. Also I don't have the machine with this setup available anymore so I would need to set up everything again to be able to build Desktop.

> Would work easily if circle ci for editor project would save the release bundle as artifact for every branch

This should be possible, currently we are already saving CI build artifacts for every PR (you need to be logged in to circle CI to be able to view the artifacts):





 



grafik

This is a great feature and makes it easy to provide demo links for testing PRs, like for this PR:
https://2006-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

A nice feature would be to have a bot which is posting for every PR

- a test build link 
- links for downloading the Desktop versions

Maybe this one is suitable: https://github.com/maputnik/editor/issues/456

**Comment by orangemug** [comment]
Merging, I will give it a proper test in `v1.7.0-beta3`

**Comment by pathmapper** [comment]
I can confirm this is working (tested on Linux). 

Added the Desktop versions to the [v1.7.0](https://github.com/maputnik/editor/releases/tag/v1.7.0) release:

grafik

**Pull request merged**
