### PR TITLE
Activate sponsor button in GitHub

### PR DESCRIPTION
**Pull request by fredj**
Displays the "❤️ Sponsor" in the repository, more info:
https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

The link is the same as the one in the README

### CODE REVIEW

**Comment by orangemug** [comment]
Sounds like a good idea to me, merging!

**Comment by orangemug** [comment]
Nice it worked, thanks @fredj now if we only had some donations :)

Screen Shot 2019-10-24 at 16 06 55

If you want to get involved more in the project feel free to suggest ideas, grab tickets etc... Just comment on anything you feel like working on. If you have time and are unsure what you would interest in, also feel free to list your skills, a can help find something. There are tons of things I can think of that would make Maputnik better other that editor contributions also

 - Documentation
 - Building a truly open source map style from https://github.com/lukasmartinelli/naturalearthtiles (rather than pay to use providers)
 - Better release notes, gifs/videos etc... so we can let people know whats going on a little more
 - UX reviews with users

Obviously it's totally up to you, just good to have people about either way. Thanks for all the effort

CC'ing @pathmapper because we should probably put that sort of statement in a contributing file or something and get better at welcoming new contributors (I'll raise a ticket separately for that)

**Comment by fredj** [comment]
Thanks for the welcome message @orangemug !

**Comment by pathmapper** [comment]
> we should probably put that sort of statement in a contributing file or something and get better at welcoming new contributors (I'll raise a ticket separately for that)

Yeah, let's do it.

> Building a truly open source map style

That's something I'm having also on my list. If someone wants to start working on this together, just let me know.

**Pull request merged**
