### PR TITLE
make docker simpler

### PR DESCRIPTION
**Pull request by morlay**
assets of frontend is built by the last `RUN`,
so we just need to host the built assets.
in node, python is required, so use python simple server to do this.

### CODE REVIEW

**Comment by orangemug** [comment]
That makes more sense, thanks.

Also welcome to Maputnik @morlay and thanks for contributing.

**Comment by orangemug** [comment]
Since we don't use the dockerfile in appveyor I'm assuming appveyor was having a bad day. Merging anyway, hopefully it'll pass... else I'll look into the issue once merged.

**Comment by pathmapper** [comment]
There is something wrong with appveyor in general: https://ci.appveyor.com/project/lukasmartinelli/editor/builds/20372093 (@orangemug could you cancel the test there?)

There was recently an [image update](https://www.appveyor.com/updates/2018/11/09/), hopefully https://github.com/maputnik/editor/pull/470/commits/7004259867741dc793c88b6066449ea1124eba08 helps.

**Comment by orangemug** [comment]
> ...could you cancel the test there?

Unfortunately I don't seem to be able to, there's no UI for me to do that... which is odd. Maybe because @lukasmartinelli is the owner of the CI env still. It's odd though because I can trigger a rebuild

**Pull request merged**
