### PR TITLE
Added new features from the mapbox-gl spec

### PR DESCRIPTION
**Pull request by orangemug**
Added support for 

 -  `text-writing-mode` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-writing-mode
 - `*-sort-key` (removed see @pathmapper comment)
   - `circle-sort-key` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-circle-circle-sort-key
   - `fill-sort-key` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-fill-fill-sort-key
   - `line-sort-key` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-line-line-sort-key

I'm not entirely sure how to test `text-writing-mode` as I'm not entirely sure what it does. However the JSON appear to update correctly and passes the mapbox-gl validation, so I'll assume it's correct

**Edit**: Also added as per @pathmapper suggestion 

 - `text-variable-anchor` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-variable-anchor
 - `text-radial-offset` - https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-radial-offset

Demo: https://1506-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html (updated)

### CODE REVIEW

**Comment by pathmapper** [comment]
Nice, maybe add also:

`text-variable-anchor` - 
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-variable-anchor

`text-radial-offset` - 
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-radial-offset

**Comment by pathmapper** [comment]
> how to test text-writing-mode

It works, you can test it on a language which supports both writing modes:

writing_mode

**Comment by orangemug** [comment]
> Nice, maybe add also:
> 
> text-variable-anchor -
> https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-variable-anchor
> 
> text-radial-offset -
> https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-radial-offset

Added

**Comment by pathmapper** [comment]
Thanks @orangemug 
The `text-*` properties are all working as expected but when a `*-sort-key` is added for a layer, it is added for all layers of the same type (tested with fill and line layers). E.g. setting the `line-sort-key` for a layer adds the same value for all line layers in the style.

**Comment by orangemug** [comment]
> E.g. setting the line-sort-key for a layer adds the same value for all line layers in the style.

This actually looks like this was a potential issue for lots of inputs, the `<LayerEditor />` didn't have `key`set which meant that react was trying to reuse DOM elements. If you changed from a layer type of `fill` to another element of `fill` it would use the same DOM element. Because of the way `<NumberInput/>` was coded, it was an uncontrolled input until a value was set it would reuse the previous value of the DOM element. 

Other issues with `<NumberInput />` was that is wasn't allowing you to set it to a `""` (empty string). So you couldn't remove it the value once set. That is also now fixed.

Fixes for testing https://1517-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Nice spot @pathmapper

**Comment by pathmapper** [comment]
Turns out that `*-sort-key` are layout properties, but it makes no sense to use directly a number there because features are sorted **within the same layer**. Instead the value would be derived from feature properties using `expressions`. So I think it makes not really sense to add these until https://github.com/maputnik/editor/issues/223 is available.

Here is an example:
https://raw.githubusercontent.com/mapbox/mapbox-gl-js/master/test/integration/render-tests/line-sort-key/literal/style.json

This example with the demo (just learned that it's possible to open a style with inline GeoJSON :smile:):
https://1517-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html?style=https://raw.githubusercontent.com/mapbox/mapbox-gl-js/master/test/integration/render-tests/line-sort-key/literal/style.json#6/0/0

**Comment by orangemug** [comment]
> Turns out that *-sort-key are layout properties, but it makes no sense to use directly a number there because features are sorted within the same layer.

Your totally correct @pathmapper my mistake. I've removed those now in this PR

> Thanks for the fixes @orangemug, these are helping us apart from this PR.

Yeah I agree lots of fixes, thanks @pathmapper for finding all the issues, I feel like we've made some real progress adding enum support and `<NumberInput />` fixes.

**Comment by pathmapper** [comment]
@orangemug thanks, looks good to me now!

**Comment by orangemug** [comment]
Thanks merging!

**Pull request merged**
