### PR TITLE
Added hillshading support

### LINKED ISSUE #262: Hillshading source/layer
It is currently not possible to add _raster_dem_ source and _hillshading_ type of layer as in this example:
https://www.mapbox.com/mapbox-gl-js/example/hillshade/
Available since mapbox-gl-js 0.43.

### PR DESCRIPTION
**Pull request by orangemug**
Related to #262. Almost there, it seems like if you load a style with hill shading you can add further hill shading layers. However if you add a hill shade layer to an empty style the mgl validator throws an error. 

See <https://224-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.kxhzGDE/build/index.html>

### CODE REVIEW

**Comment by orangemug** [comment]
Ah I see the issue, source is not getting added correctly. Will fix shortly

**Comment by paumas** [comment]
You forgot to change https://github.com/maputnik/editor/blob/master/src/components/layers/LayerEditor.jsx#L141 line and https://github.com/maputnik/editor/blob/master/src/components/map/MapboxGlMap.jsx#L41 line.

**Comment by orangemug** [comment]
@paumas good catch (oh and hi!). I fixed some other issues. Headed out now, will fix those issues in the morning.

Latest build <https://223-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.cVVwEUy/build/index.html#6.67/47.154/9.099>

**Comment by tomass** [comment]
Thank you! It works:
paveikslas

**Comment by orangemug** [comment]
So a few more things we need to fix pre-merge.

 - mapbox-gl-inspect
   - <https://github.com/lukasmartinelli/mapbox-gl-inspect/blob/19eeb49e768be67095aad7d51157af33e19067b5/lib/MapboxInspect.js#L19-L34>
   - <https://github.com/lukasmartinelli/mapbox-gl-inspect/blob/d90a3238fdc64e535d8b7ddab8f5644fd8bb6fec/lib/stylegen.js#L124-L126>
 - Decide on a unique icon <https://github.com/maputnik/editor/pull/263/files#diff-5c1f9b6d6df7258739fbe3c2ca927a46R21>

**Comment by orangemug** [comment]
@lukasmartinelli did you make these icons yourself or are they from a collection?
 
Reference: https://github.com/orangemug/editor/blob/38e07864631fd88f3b77ec7e34fc77589652814b/src/components/icons/FillIcon.jsx#L9

**Comment by orangemug** [comment]
Latest build <https://224-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.kxhzGDE/build/index.html>

**Comment by orangemug** [comment]
Note: Using `github:orangemug/mapbox-gl-inspect#fix/only-vector-sources` until merge of https://github.com/lukasmartinelli/mapbox-gl-inspect/pull/11

**Pull request merged**
