### PR TITLE
Update all the deps

### PR DESCRIPTION
**Pull request by orangemug**
I've updated all the `dependencies`/`devDependencies` in the `package.json`

Demo <https://2244-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0/0/0>

It looks like the webdriver tests are failing to close modals, so I'll need to hunt that error down and fix it. 

Does, anybody want to give it a run through, see if there are any more regressions?

### CODE REVIEW

**Comment by orangemug** [comment]
> 4 successful checks

The failing tests from circleci aren't showing up in the UI 🤔

**Comment by pathmapper** [comment]
> The failing tests from circleci aren't showing up in the UI

I guess this is because you configured circle CI somehow that it also runs on commits in your fork and these are not run again here:

- https://github.com/orangemug/editor/tree/maintenance/update-deps-20200217-v2
- https://circleci.com/gh/orangemug/editor/2244?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I noticed this also on some of your other PRs.

**Comment by pathmapper** [comment]
> Does, anybody want to give it a run through, see if there are any more regressions?

Maybe resolve the conflicts first?

**Comment by orangemug** [comment]
@pathmapper resolved conflicts and failing tests fixed.

**Comment by pathmapper** [comment]
Meanwhile GL JS `v1.8.0` and Style Spec `13.12.0` are released:
https://github.com/mapbox/mapbox-gl-js/releases

@orangemug in Firefox the inspect background is white, in Chrome it is still black :confused: 

grafik

**Comment by pathmapper** [comment]
Errors in inspect:

Chrome:
grafik

Firefox:
grafik

In Master inspect is disabled in FF but works in Chrome:
https://2198-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

So this might be unrelated to the deps update.

**Comment by pathmapper** [comment]
@orangemug ups, raised the minzoom for the background while testing, that's why it wasn't displayed in FF in inspect :)

**Comment by orangemug** [comment]
Thanks @pathmapper 

> ...in Firefox the inspect background is white, in Chrome it is still black 😕

Yeah only in FF on linux also, in MacOS it's black. Very odd I'll take a look. 

> In Master inspect is disabled in FF but works in Chrome

I'm not sure what you mean by this? Can you clarify

**Comment by orangemug** [comment]
Oh the latest build with the newly released mapbox-gl seems to have fixed the inspect color issue for me.

Latest build <https://2289-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0/0/0>

**Comment by pathmapper** [comment]
> Can you clarify


Peek 2020-02-21 10-19


But this is fixed with this PR / the deps update.
Maybe the browser detection based on user agent was nor working correctly.

**Comment by orangemug** [comment]
@pathmapper can you give it a try in the latest build <https://2289-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0/0/0>

**Comment by pathmapper** [comment]
This PR Looks good to me.

Regarding these error messages in inspect mode:
https://github.com/maputnik/editor/pull/619#issuecomment-589561518

Looks like these are unrelated to this PR - I don't get these in Maputnik `v1.6.1` but they appear also on `master`. I can't see that anything is broken because of these errors.

**Comment by orangemug** [comment]
> Looks like these are unrelated to this PR - I don't get these in Maputnik v1.6.1 but they appear also on master. I can't see that anything is broken because of these errors.

Yeah I think lets merge and I can clean up all the warnings and any console errors pre-release. Hopefully planning a beta release next week with [expressions](https://github.com/maputnik/editor/pull/620) added. Hopefully then we can drag some other people in to test because expression support as well as it's a fairly big code change. I think it's about time I printed some Maputnik stickers (swag) to celebrate 😄

**Comment by pathmapper** [comment]
> Maputnik stickers

Good idea, I could also print some and distribute them at https://www.fossgis-konferenz.de/2020/.

**Pull request merged**
