### PR TITLE
814/remove mapbox references

### LINKED ISSUE #814: Remove outdated references to mapbox
**Maputnik version**: master
**Browser**:
**OS**:

**Description of the bug**:

#812 converted maputnik to use maplibre instead of mapbox, but as @tordans noticed, the README.md, ModalSettings.jsx and [many other files](https://github.com/search?q=repo%3Amaputnik%2Feditor%20mapbox&type=code) still reference mapbox. Most of these references are now outdated.

### PR DESCRIPTION
**Pull request by kevinschaul**
Fixes #814

### CODE REVIEW

**Review by nyurik — APPROVED** [review]
awesome work, thanks!!!

**Review by lseelenbinder — APPROVED** [review]
LGTM.

Thanks! 🚀

**Comment by kevinschaul** [comment]
Thanks! Just fixed a few references I missed, in storybook and the webpack configs. If all passes, I think this is ready for a merge.

**Comment by nyurik** [comment]
thanks @kevinschaul !!!

**Pull request merged**
