### PR TITLE
Show error if style fails to load and disabled button if input is empty

### LINKED ISSUE #396: Notification if no style was loaded
If no or an invalid URL was inserted before click on _Open URL_, the _Loading style_ modal shows up and immediately closes on its own. There should be a notification to the user that no style was loaded.

Ref: https://github.com/maputnik/editor/issues/393#issuecomment-423851803

### PR DESCRIPTION
**Pull request by orangemug**
Fixes #396

Take a look @pathmapper

### CODE REVIEW

**Comment by pathmapper** [comment]
@orangemug looks good in general, only one thing:
If the modal is opened again after a fail the button is not disabled anymore if input is empty.

**Comment by orangemug** [comment]
@pathmapper good spot. The latest commit fixes that issue <https://972-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

**Comment by pathmapper** [comment]
@orangemug perfect!

**Comment by orangemug** [comment]
Thanks for testing

**Pull request merged**
