### PR TITLE
Fix to add error notice when uploading invalid JSON

### LINKED ISSUE #54: No feedback when loading local Style with invalid JSON

### PR DESCRIPTION
**Pull request by orangemug**
Fixes #54

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
I gave you admin rights on the org @orangemug.
Thanks so much for the fix.

giphy 13

**Comment by orangemug** [comment]
> I gave you admin rights on the org @orangemug.

Hey @lukasmartinelli, was this a suggestion that I should merge my own PR's? If so I've always tried to keep away from merging my own PR's on projects were I'm not the only contributor. Reason being that it prevents mistakes/bad ideas getting into the repo.

**Comment by lukasmartinelli** [comment]
> Hey @lukasmartinelli, was this a suggestion that I should merge my own PR's? If so I've always tried to keep away from merging my own PR's on projects were I'm not the only contributor. Reason being that it prevents mistakes/bad ideas getting into the repo.

Oh no. Sorry. I will happily merge and review PRs!
But you have the option to merge them yourselves if you so choose. Or create new repos to split something out. Or add new people. Or whatever else I cannot think of now.

**Comment by orangemug** [comment]
Ok thanks for clarifying, I think a visual difftool might be on its way shortly...

**Pull request merged**
