### PR TITLE
A few minor lints

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Comment by HarelM** [comment]
Did you manually fix this?
There is a PR with tests refactoring coming up which I don't want to resolve conflicts on just yet, see:
https://github.com/HarelM/editor/pull/5/files
So let's wait a bit with this.
Cc: @shellyDCMS can you open your PR against this repo instead?

**Comment by nyurik** [comment]
Mostly by hand, but using various tools to find them

**Comment by nyurik** [comment]
Its ok - i can rebase this PR later on once your refactorings are merged in

**Comment by HarelM** [comment]
@nyurik I still think there are good corrections here, but generally speaking the path forward (besides typos) is using lint rules and `--fix` flag to change according to the new rule.
I would consider closing this PR and opening a new one, probably easier...
Your call.

**Pull request closed without merging**
