### PR TITLE
Add support for raw GeoJSON as source

### LINKED ISSUE #559: Ability to add inline GeoJSON as source
https://github.com/maputnik/editor/pull/556#issuecomment-541537957 brought me to the idea that it would be a handy feature if it would be possible to add inline GeoJSON as source.

Currently it's only possible to add GeoJSON using a URL to a GeoJSON file.

This could be implemented by adding a new option to the _Source Type_ dropdown.

After selecting this new option it would be possible to enter, paste a GeoJSON object and maybe also select a GeoJSON file which would be added as inline GeoJSON source to the style (a validity check for the GeoJSON would be useful before adding it).

### PR DESCRIPTION
**Pull request by orangemug**
Added support for raw GeoJSON to the editor along with sizing edit to make the 'input block labels' take up only 30% of the space in the DataSources modal. 

Screenshot

Screen Shot 2019-10-19 at 13 14 26

Demo: https://1604-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Fixes #559

### CODE REVIEW

**Comment by pathmapper** [comment]
Good idea to use the JSNO editor here @orangemug .

It general it works great, really like your implementation, some findings and thoughts:

- If there is a syntax error and you hover over the lint-marker-error icon (white cross on red circle), the parse error note which appears is behind the source modal (should be related to the z-index).
image

- On a fresh loaded demo, if you first choose `GeoJSON (JSON)` and then `GeoJSON (URL)` from the Source Type dropdown, it shows `[object Object]` in the GeoJSON URL field instead of http://localhost:3000/geojson.json
URL_object_object

- If you switch from `GeoJSON (URL)` to `GeoJSON (JSON)`, the URL is used for the GeoJSON field. 
url_for_json

- After a `GeoJSON (JSON)` source is added, it is shown under `Active Sources` and the raw GeoJSON is visible which is great in general. Maybe it would be possible to collapse/expand the raw GeoJSON there. For raw GeoJSON with a lot of code lines, there is currently a lot of scrolling needed if you want to add another source.

**Comment by orangemug** [comment]
> If there is a syntax error and you hover over the lint-marker-error icon (white cross on red circle), the parse error note which appears is behind the source modal (should be related to the z-index).

Fixed

> On a fresh loaded demo, if you first choose GeoJSON (JSON) and then GeoJSON (URL) from the Source Type dropdown, it shows [object Object] in the GeoJSON URL field instead of http://localhost:3000/geojson.json

Fixed

> If you switch from GeoJSON (URL) to GeoJSON (JSON), the URL is used for the GeoJSON field.

Fixed

> After a GeoJSON (JSON) source is added, it is shown under Active Sources and the raw GeoJSON is visible which is great in general. Maybe it would be possible to collapse/expand the raw GeoJSON there. For raw GeoJSON with a lot of code lines, there is currently a lot of scrolling needed if you want to add another source.

I've added `max-height: 200px; overflow: auto;` to the `<JSONEditor/>` within the data sources modal.

Demo: https://1627-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

**Comment by pathmapper** [comment]
Thanks @orangemug, this is really cool, looks good to me.

**Comment by orangemug** [comment]
Thanks @pathmapper, merging!

**Pull request merged**
