### PR TITLE
Added support for more root level properties

### PR DESCRIPTION
**Pull request by orangemug**
@fredj @pathmapper as a fix for #560 how about adding them to the style settings? 

Screen Shot 2019-10-16 at 07 44 48

Demo: https://1538-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

### CODE REVIEW

**Comment by fredj** [comment]
Very nice, thanks @orangemug !

May I suggest to keep the "Style Renderer" option at the bottom of the list?

**Comment by orangemug** [comment]
@fredj @pathmapper also added support for the root level 'light' properties

Screen Shot 2019-10-16 at 08 27 56

**Comment by orangemug** [comment]
> May I suggest to keep the "Style Renderer" option at the bottom of the list?

Done see screenshot above

**Comment by pathmapper** [comment]
@orangemug great, closes also https://github.com/maputnik/editor/issues/440.

- For `Center` maybe add labeling which indicates which field is `lon` and which `lat` ?
- For `Light Position`  maybe add labelling `r`, `a`, `p` to make clear which field belongs to which value?

I'll do some more testing.

**Comment by pathmapper** [comment]
Some more findings and thoughts:

- `Light anchor` defaults to `viewport` (currently `map` is highlighted as default)
- Add also `transition`: https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-transition
- When the `Style Settings` modal is open, the map is darkened a bit, which alters the effect of the light source. Not sure if we want to change this, but currently there is a need to close the `Style Settings` modal to see the _real_ effect.  
- Not needed for this PR but just wanted to mention it: A nice feature would be a button in the `Settings Modal`, which populates the values for `center`, `zoom`, `pitch` and `bearing` with the values from the URL hash.

**Comment by fredj** [comment]
> Light anchor defaults to viewport (currently map is highlighted as default)

It's already the default value but it looks like the `default` property is not used in the [EnumInput](https://github.com/maputnik/editor/blob/95e205943af1653f98e72c51e34a8b786cd0004e/src/components/inputs/EnumInput.jsx#L21) component

**Comment by orangemug** [comment]
> Add also transition: https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-transition

Fixed in https://github.com/maputnik/editor/pull/563/commits/d0a47bd1226f4c7099f7d97fd374b6902b9381d4

> `Light anchor` defaults to `viewport` (currently `map` is highlighted as default)

Fixed in https://github.com/maputnik/editor/pull/563/commits/8c760bb8108dbc8991f2d918f5d920ca7c0726d0

Found another bug: You also can't remove a property once set, for example set 'Light intensity' then try and remove it. I'll have a go at fixing that later.

Thanks for all the help @fredj @pathmapper

**Comment by orangemug** [comment]
New build: https://1565-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

**Comment by pathmapper** [comment]
The `Light position` and `Style Renderer` tooltips are not fully visible and when scrolled down, the scroll position is set back to the initial position.

tooltip_issue

**Comment by orangemug** [comment]
> This issue exists also for some tooltips of the Data Sources modal.

If you collapse the JSON editor on a layer editing panel it's also an issue there as well. I think we should either find a good react tooltip library or alternatively a different UI for help text. I might be better to, on hover show a `?` next to the label and then on click show link to the place in the mapbox-gl docs (or our own render of the mapbox-gl docs)

**Comment by pathmapper** [comment]
All right, moved this to https://github.com/maputnik/editor/issues/567

**Comment by fredj** [comment]
I really hope that the ability to set the `center` property will come back !

**Comment by orangemug** [comment]
Yeah sorry, I noticed it was actually a little broken last night, so remove it temporarily. Yeah I plan to work on it next time a get the chance. Sorry I didn't have a chance to leave a comment last night @fredj.

A little description of the issue, so the `<ArrayInput />` component allows you to enter a number of values as a single property, so for example a coordinate `[x,y]` or `[x,y,z]`, unfortunately that `<ArrayInput />` doesn't really work because if you enter a value in `x` then move focus to `y` you    end up triggering a change event. That in turn does validation on the value `[x,y,z]` (via mapbox-gl spec validator), which is invalid because you haven't yet entered anything in `y` or `z`.

Note this kind of worked for the `center` because if you entered a value in `x` (for example `1.1` the value would be `[1.1]`, the `center` validation passes for both `[x]` and `[x,y]`. However if you enter a value in `y` first the value would be `[undefined, 1.1]` which would fail validation

The 'light position' didn't work at all because the validation asserts that the length must be `3` so you enter a value in `x` it'll fail validation right away.

The solution I'm kind of leaning towards is making a 'coordinate' input type only triggering the `onChange` event when all the inputs contain a value.

Any suggestions or comments welcome.

**Comment by fredj** [comment]
Thanks for the explanations and your work on this pull request @orangemug

**Comment by fredj** [comment]
> Any suggestions or comments welcome.

Could it be implemented using the same `state.editing` / `getDerivedStateFromProps` technique used in `StringInput`?
And `editing` is true if `this.props.value` length is the same as `this.props.length` (and without `undefined` value).

(I've a very limited experience in react, so it's probably a wrong idea!)

**Comment by orangemug** [comment]
So I've implemented an idea of what I think `<ArrayInput />` should look like, based off what @fredj commented. So what it now does is it doesn't trigger `onChange` with a value until all the inputs are filled with values. If you fill `x` but not `y` the `onChange`event will trigger with `onChange(undefined)` effectively removing the value from the JSON. 

I've also made fixes to the array input to allow for default values and removing of values, which fixes bugs with `*-translate`

Demo: https://1592-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

Let me know what you think @pathmapper @fredj

**Comment by pathmapper** [comment]
@orangemug thanks, works great.

If you remove the values for `light` (so that the default values are used), `"light": {}` remains in the style which is not needed. Same for `transition`. But it could also stay like it is now.

**Comment by fredj** [comment]
looks very good, thanks again @orangemug

**Comment by orangemug** [comment]
> If you remove the custom values for light (so that the default values are used), "light": {} remains in the style which is not needed. Same for transition. But the PR could also be merged like it is now.

Nice spot, lets merge this now, I'll fix that in another PR.

Thanks for all the help @fredj @pathmapper, merging!

**Pull request merged**
