### PR TITLE
Moved to using react-accessible-accordion for <LayerEditorGroup/>

### LINKED ISSUE #321: Accessible collapsable layer groups
The collapsable 'layer groups' when editing a layer are not currently keyboard accessible.

There is an existing pull request for this <https://github.com/maputnik/editor/pull/299>. However as it says in that ticket <https://github.com/springload/react-accessible-accordion> is probably a better approach.

### PR DESCRIPTION
**Pull request by orangemug**
This does remove the animation, but that seems like a small price for accessibility, we can work out how to put back in animation later.

Screenshot 2020-03-28 at 12 58 04

Demo <https://2383-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

Fixes #321

### CODE REVIEW

**Comment by pathmapper** [comment]
> that seems like a small price for accessibility, we can work out how to put back in animation later.

@orangemug agree, what about 
https://github.com/maputnik/editor/blob/master/src/components/layers/LayerListGroup.jsx ?

**Comment by orangemug** [comment]
`<LayerListGroup/>` is slightly different it needs to be a 'tree view', see #320. I've got something partially working for that but it's slight more involved.

**Comment by pathmapper** [comment]
Thanks @orangemug, looks good to merge.

**Comment by orangemug** [comment]
Thanks, merging!

**Pull request merged**
