### PR TITLE
Adding mac keyboard bindings

### PR DESCRIPTION
**Pull request by ziveo**
This PR is adding missing mac keyboard bindings

### CODE REVIEW

**Comment by orangemug** [comment]
Hi @ziveo thanks for the pull request, much appreciated. How about using something like

```
const isMac = navigator.platform.toUpperCase().indexOf('MAC')>=0;
if(isMac) {
  // Mac bindings...
}
else {
  // Non mac bindings...
}
```

So we only bind for the environment we're interested in?

Ref: https://stackoverflow.com/questions/10527983/best-way-to-detect-mac-os-x-or-windows-computers-with-javascript-or-jquery

**Comment by orangemug** [comment]
Ah actually it looks like we can just use `mod`. See https://github.com/ccampbell/mousetrap/blob/fec446031c88cfcbd4cbdbfcc6c88f16fae4a50b/mousetrap.js#L135

**Comment by ziveo** [comment]
I think this will work

**Comment by orangemug** [comment]
Thanks @ziveo merging

**Comment by orangemug** [comment]
...also @ziveo if you have time please share what you're using Maputnik for over in ticket #164

**Pull request merged**
