### PR TITLE
Further OpenLayers improvements

### LINKED ISSUE #254: Zoom display missing from map with openlayers renderer
The zoom display as added in PR #179 is missing from the map when using the openlayers renderer

### PR DESCRIPTION
**Pull request by orangemug**
Over the weekend I was trying to get an antarctic map rendering with `ol-mapbox-style` and some vector tiles that I've projected using `ogr2ogr`. I have a very hacked together version of that 'kinda works' (more on that in later PR's), however along the way I made a couple of improvements to the OL renderer.  

I've added

 - Disable inspect mode for openlayers render as it doesn't work
 - Added debug toolbox to tell me the current state of the openlayers map (mainly for debugging projections, but generally useful), note this is behind a setting in the debug modal
 - Zoom display UI, the same as the mapbox-gl renderer
 - Fixed rendering of rotate UI

Screenshot

Screen Shot 2019-05-29 at 19 24 45

Fixes #254

### CODE REVIEW

**Comment by pathmapper** [comment]
One comment, otherwise it's working great and closes https://github.com/maputnik/editor/issues/254.

If you switch from the mgl renderer in inspect mode to the ol renderer, the inspect mode is selected (but not working of course). It shouldn't be selected.

image

**Comment by orangemug** [comment]
> If you switch from the mgl renderer in inspect mode to the ol renderer, the inspect mode is selected (but not working of course). It shouldn't be selected.

@pathmapper it now resets map state on renderer change, see latest at https://1391-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html

**Comment by pathmapper** [comment]
@orangemug nice! Should be good to merge now, this kind of failing appeveyor test happens from time to time.

**Comment by orangemug** [comment]
Thanks @pathmapper, merging!

**Pull request merged**
