### PR TITLE
Survey (#328)

### PR DESCRIPTION
**Pull request by gregorywolanski**
Elements promoting the survey inside Maputnik

### CODE REVIEW

**Comment by orangemug** [comment]
I'm away on holiday for the next 10 days. I might be a little delayed in reviewing it, I'll try to find the time.

**Comment by orangemug** [comment]
Hey @gregorywolanski the pull request looks great!

A few comments

 - I think clicking 'Take the Maputnik Survey' should close the modal
 - Clicking 'Take the Maputnik Survey' should set the 'survey' cookie so the popup doesn't show again on startup
 - `src/components/modals/SurveyModal.jsx` inline styles should be added to a `.scss` files. I've been using [BEM](http://getbem.com/naming/) syntax for [recent css additions](https://github.com/maputnik/editor/blob/master/src/styles/_layer.scss#L184-L204). So classes would be something like `.modal-survey`, `.modal-survey__container`, `.modal-survey__logo`, `.modal-survey__text-highlight`  
 - `.green` css class is a bit abstract, I suggest using `.modal-survey__text-highlight` (see above)

**Comment by orangemug** [comment]
Also we could use localstorage rather than a cookie. This reduces dependencies for Maputnik

**Comment by gregorywolanski** [comment]
@orangemug Excuse me, I messed up something with git.

**Pull request closed without merging**
