### PR TITLE
Fix for updating available sources cache when updating style

### LINKED ISSUE #533: Add layer modal - available sources not updated
The available sources in the `add layer modal` (after clicking on the `Source` field) are not updated after removing or adding a source via the `source modal`.

Currently there is a need to refresh the browser tab (F5) to update these values.

Similar issue: https://github.com/maputnik/editor/issues/403

image

### PR DESCRIPTION
**Pull request by orangemug**
Demo <https://2611-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>

Fixes #533

### CODE REVIEW

**Comment by pathmapper** [comment]
Nice @orangemug, the available sources are now updated. :tada: 

One thing: The add layer modal _remembers_ the last used source, also for cases where it is not available anymore. Here is a demonstration where the `openmaptiles` source is still shown in the add layer modal but the only available source is `composite`:

pr_684

**Comment by orangemug** [comment]
> The add layer modal remembers the last used source, also for cases where it is not available anymore...

@pathmapper fixed in latest commit, demo <https://2632-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>

**Comment by pathmapper** [comment]
Thanks @orangemug, looks good :+1:

**Comment by orangemug** [comment]
Thanks, merging

**Pull request merged**
