### PR TITLE
Initial work to convert from Mapbox GL v1.13 to MapLibre v2.4.0.

### LINKED ISSUE #781: Support for maplibre
Since this topic was raised in https://github.com/maputnik/editor/issues/775, this issue is to discuss about support for maplibre: https://github.com/maplibre/maplibre-gl-js

- mapbox-gl version 1.x. -> backward compatible to mapbox-gl

- maplibre-gl version 2 -> non-backward compatible

### PR DESCRIPTION
**Pull request by lseelenbinder**
This is likely to be a fairly long running PR to switch the primary rendering library from legacy Mapbox GL v1.13 (which won't be receiving improvements or updates) to MapLibre v2.4.0 (the free & community-driven fork).

Most changes are superficial related to different package names.

TODO:

- [ ] Ensure tests run and pass
- [ ] Throughly test functionality visually

Fixes #781.

### CODE REVIEW

**Comment by lbogdan** [comment]
This is waiting for user input when [building in CodeSandbox CI](https://ci.codesandbox.io/status/maputnik/editor/pr/789/builds/309179):

```
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by lseelenbinder** [comment]
I noticed that @lbogdan… I didn't adjust the workflows. I'll see if there's anything I can fix…

**Comment by nyurik** [comment]
@lseelenbinder I added you to the project to make it easier to run PRs etc

**Comment by HarelM** [comment]
+1, I would love to see this in maputnik as well.
Tag me if there's something you need help with.

**Comment by klokan** [comment]
Great effort @lseelenbinder!

**Comment by ohrie** [comment]
@lseelenbinder What's the status on this PR? Is it possible to support you, if so, how?

**Comment by lseelenbinder** [comment]
@ohrie I think support with an approach for testing and ensuring this didn't break anything is the biggest way someone can help. I did the initial transition work, but haven't had the chance to get back to it to ensure no breakage and fix tests since then.

It's also not clear to me if we have full community support for this change, but I think @nyurik has merge rights and there isn't much activity otherwise, so we can probably proceed?

**Comment by nyurik** [comment]
i'll be happy to merge it once there is no more conflict and passes the tests

**Comment by HarelM** [comment]
Cool!

**Pull request merged**
